---
- name: My First Playbook
  hosts: all
  become: true
  any_errors_fatal: true
  vars_files: ./mysecret.yml

  tasks:
  - name: Ping My Servers
    ping:

  - name: Verify OS_Family
    debug: var=ansible_os_family

  - name: Configure sshd_config
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '#ClientAliveInterval 0'
      line: 'ClientAliveInterval 300'
      #shell: sed -i '/#ClientAliveInterval 0/a ClientAliveInterval 300' /etc/ssh/sshd_config
    notify: reload sshd.service

#####sudo apt-get update && sudo apt-get dist-upgrade -y
  - block:
      - name: sudo apt-get update
        apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
      - name: sudo apt-get dist-upgrade
        apt: upgrade=dist force_apt_get=yes
    when: ansible_os_family=="Debian"

#####sudo yum update -y
  - block:
      - name: sudo yum update cache
        yum: update_cache=yes
      - name: sudo yum update all packages
        yum: name=* state=latest
      - name: sudo yum install epel-release
        yum: name=epel-release state=latest
    when: ansible_os_family=="RedHat"

#####adduser anton on Ubuntu
  - block:
      - name: adduser anton to sudo group
        user:
          name: anton
          password: "{{ anton_sudo_password | password_hash('sha512') }}"
          shell: /bin/bash
          groups: sudo
          append: true
          update_password: on_create 
    when: ansible_os_family=="Debian"

#####adduser anton on CentOS
  - block:
      - name: adduser anton to wheel group
        user:
          name: anton
          password: "{{ anton_sudo_password | password_hash('sha512') }}"
          shell: /bin/bash
          groups: wheel
          append: true 
          update_password: on_create
    when: ansible_os_family=="RedHat"

#####install packages on Ubuntu
  - block:
      - name: sudo apt-get install packages
        apt:
          name: ['ansible', 'git', 'htop', 'tree', 'net-tools', 'mc', 'nano', 'wget', 'collectd', 'yamllint', 'locales', 'language-pack-ru-base', 'language-pack-ru']
          state: latest
          force_apt_get: yes
    when: ansible_os_family=="Debian"

#####install packages on CentOS
  - block:
      - name: sudo yum install packages
        yum:
          name: ['ansible', 'git', 'htop', 'tree', 'net-tools', 'mc', 'nano', 'wget', 'collectd', 'yamllint']
          state: latest
    when: ansible_os_family=="RedHat"

#####Create folders on Ubuntu
  - block:
      - name: Create .ssh folder
        file: path=/home/anton/.ssh state=directory mode=0755

      - name: Create ansible folder
        file: path=/home/anton/ansible state=directory mode=0755

      - name: Create gitproject folder
        file: path=/home/anton/gitproject state=directory mode=0755

      - name: Create files folder
        file: path=/home/anton/files state=directory mode=0755
    when: ansible_os_family=="Debian"

#####Create folders on CentOS
  - block:
      - name: Create .ssh folder
        file: path=/home/anton/.ssh state=directory mode=0755

      - name: Create ansible folder
        file: path=/home/anton/ansible state=directory mode=0755

      - name: Create gitproject folder
        file: path=/home/anton/gitproject state=directory mode=0755

      - name: Create files folder
        file: path=/home/anton/files state=directory mode=0755
    when: ansible_os_family=="RedHat"

#####adduser ansible on Ubuntu
  - block:
      - name: adduser ansible to sudo group
        user:
          name: ansible
          password: "{{ ansible_sudo_password | password_hash('sha512') }}"
          shell: /bin/bash
          groups: sudo
          append: true
          update_password: on_create
    when: ansible_os_family=="Debian"

#####adduser ansible on CentOS
  - block:
      - name: adduser ansible to wheel group
        user:
          name: ansible
          password: "{{ ansible_sudo_password | password_hash('sha512') }}"
          shell: /bin/bash
          groups: wheel
          append: true
          update_password: on_create
    when: ansible_os_family=="RedHat"

#####Install && Start Web-Server on Ubuntu
  - block:
      - name: Install apache2 to Ubuntu
        apt: name=apache2 state=latest
      - name: Start apache2 service
        service: name=apache2 state=started enabled=yes
    when: ansible_os_family=="Debian"

#####Install && Start Web-Server on CentOS
  - block:
      - name: Install httpd to CentOS
        yum: name=httpd state=latest
      - name: Start httpd service
        service: name=httpd state=started enabled=yes
    when: ansible_os_family=="RedHat"

#####Handlers
  handlers:
  - name: reload sshd.service
    service: name=sshd.service state=reloaded
